import { RegistrationService } from '../services/registration.service';
import { UserRepository } from '../repositories/user.repository';
import { getIdentityProvider } from '../../../shared/services/identity.service';
import { sendPasswordResetEmail } from '../../../shared/utils/mailer';
import type { User } from '../entities/user.entity';

jest.mock('../repositories/user.repository', () => ({
  UserRepository: { Instance: { findByEmail: jest.fn() } },
}));
jest.mock('../repositories/emailVerification.repository', () => ({
  EmailVerificationRepository: { Instance: {} },
  generateCode: jest.fn(),
  hashCode: jest.fn(),
}));
jest.mock('../../../shared/services/identity.service', () => ({
  getIdentityProvider: jest.fn(),
}));
jest.mock('../../../shared/utils/mailer', () => ({
  sendPasswordResetEmail: jest.fn().mockResolvedValue(undefined),
  sendSchoolReadyEmail: jest.fn().mockResolvedValue(undefined),
  sendVerificationEmail: jest.fn().mockResolvedValue(undefined),
}));

const users = UserRepository.Instance as jest.Mocked<typeof UserRepository.Instance>;
const identity = getIdentityProvider as jest.MockedFunction<typeof getIdentityProvider>;
const sendReset = sendPasswordResetEmail as jest.MockedFunction<typeof sendPasswordResetEmail>;

const generatePasswordResetLink = jest.fn();

function user(): User {
  return {
    id: 'usr_1',
    email: 'chidinma.eze@brightfield.edu.ng',
    firstName: 'Chidinma',
    lastName: 'Eze',
  } as User;
}

/** The email is fired without being awaited, so let the microtask queue drain. */
const settle = () => new Promise((resolve) => setImmediate(resolve));

beforeEach(() => {
  identity.mockReturnValue({
    generatePasswordResetLink,
  } as unknown as ReturnType<typeof getIdentityProvider>);
});

/**
 * The reset link is generated by the identity provider and sent by us, so it
 * arrives in the same template as every other message from the school rather
 * than unbranded from a service the recipient has never heard of.
 */
describe('RegistrationService.forgotPassword', () => {
  it('emails the generated link to an address that has an account', async () => {
    users.findByEmail.mockResolvedValue(user());
    generatePasswordResetLink.mockResolvedValue('https://auth.test/reset?oobCode=abc');

    await RegistrationService.Instance.forgotPassword({
      email: 'chidinma.eze@brightfield.edu.ng',
    });
    await settle();

    expect(sendReset).toHaveBeenCalledWith(
      expect.objectContaining({
        to: 'chidinma.eze@brightfield.edu.ng',
        firstName: 'Chidinma',
        resetUrl: 'https://auth.test/reset?oobCode=abc',
      }),
    );
  });

  /*
    An answer that differed would turn this endpoint into a way to work out
    which of a school's parents and staff are registered.
  */
  it('answers the same way for an address with no account, and sends nothing', async () => {
    users.findByEmail.mockResolvedValue(null);

    const result = await RegistrationService.Instance.forgotPassword({
      email: 'nobody@nowhere.test',
    });
    await settle();

    expect(result).toEqual({ expiresInHours: 1 });
    expect(sendReset).not.toHaveBeenCalled();
  });

  it('sends nothing when the provider has no credential for the address', async () => {
    users.findByEmail.mockResolvedValue(user());
    generatePasswordResetLink.mockResolvedValue(null);

    await RegistrationService.Instance.forgotPassword({
      email: 'chidinma.eze@brightfield.edu.ng',
    });
    await settle();

    expect(sendReset).not.toHaveBeenCalled();
  });

  it('still answers normally when the provider fails outright', async () => {
    users.findByEmail.mockResolvedValue(user());
    generatePasswordResetLink.mockRejectedValue(new Error('Firebase is unreachable'));

    const result = await RegistrationService.Instance.forgotPassword({
      email: 'chidinma.eze@brightfield.edu.ng',
    });
    await settle();

    expect(result).toEqual({ expiresInHours: 1 });
    expect(sendReset).not.toHaveBeenCalled();
  });
});
